### ISSUE TITLE
엑셀 파일과 DB 동기화 - 동현

### ISSUE THREAD

**Issue by rlrlaa123** [rlrlaa123/DelionServer#4]

**Comment by rlrlaa123** [comment]
@kmju1997 
데이터 불러오는거랑 permission 이런거는 다 완성해서 이제 csv&DB 동기화만 하면 되는데 이거는 만나서 같이 하는게 어때? 이것만 다하면 드디어 배포 후 테스팅이다...

**Comment by rlrlaa123** [comment]
[django-csvimport](https://github.com/edcrewe/django-csvimport)
Django csvimport 라는 library가 있는데, admin 페이지에서 csv파일 저장하면 디비로 값이 저장되는 방식으로 처리하는듯?

**Comment by kmju1997** [comment]
아 그런 라이브러리가 있어요? 그럼 그거 찾아봐야겠네요 일단 오케이

**Comment by rlrlaa123** [comment]
이번주 주말은 힘들어?ㅠ

**Comment by rlrlaa123** [comment]
Django 와 합치는 것은 #13 Issue로 전환
