### ISSUE TITLE
data 수정 완료 후 의논해야할 점 + 코드 수정 부분  

### ISSUE THREAD

**Issue by kmju1997** [rlrlaa123/DelionServer#7]
1. foreign key 추가 - 첨부한 사진 처럼 model.py 수정 필요
2. extender_menu / special_num field의 앱에서의 사용 확인한 후 추가 여부 결정

**Comment by kmju1997** [comment]
![kakaotalk_20170719_194053214](https://user-images.githubusercontent.com/19407354/28366251-daca1240-6cc6-11e7-8fd1-4d66c0213d8d.jpg)

**Comment by rlrlaa123** [comment]
1. Category는 굳이 foreign key안해도 될 것 같다고 지난번에 얘기했던 것 같은데, 별로 중요하지 않은 테이블 필드에 가장 중요한 menu 정보들이 묶여 있어서 위험할 것 같다고
2. extender_menu는 사용되지만, special_num은 사용 안되서 빼도 될듯

* https://github.com/Jeongah-Shin/delion 정아 레포지토리에서 안드코드 너도 볼 수 있다.

**Comment by kmju1997** [comment]
근데 카테고리 - shop은 안해도 shop - menu 간의 pk fk 관계는 있어야 할거 같아요!
딜라이온 DB 보니까 shop내용은 없는데 menu 데이터가 존재하고 있는 경우가 있더라구요

**Comment by rlrlaa123** [comment]
ㅇㅇ shop menu는 당연히 foreign key 되 잇징 그럼 이거 이슈 close 할게
