### ISSUE TITLE
beautifulsoup을 이용한 database에 csv 파일 형식 데이터 추가 

### ISSUE THREAD

**Issue by kmju1997** [rlrlaa123/DelionServer#8]
admin을 통해서 파일 추가 -> 파일을 추가함과 동시에 data_add.py 파일 실행 -> data_add.py 파일은 현재 제일 최근에 추가한 파일을 불러와 data_add.py 안의 동작을 실행하여 데이터를 데이터베이스에 입력...
정도가 생각한 방법이고 일단 필수적으로 수정해야 할 부분과 의논할 부분 첨부합니다

> 수정해야 할 부분
1. csv파일을 저장할 수 있는 model이 필요, 따라서 model에 csv를 추가 - field는 파일형식으로 하나만 존재하면 될 것 같음 (csv -  csv(file))
2. data_add.py 만들기
불러오기 -> csv 판단 (어떤 모델의 csv인가?) -> parsing -> for문 이용한 인스턴트 생성 및 입력

> 생각해야 할 동작 부분의 의문
1. csv 인스턴트가 생성되었을 경우에 data_add.py가 실행되도록 코딩해야하는데 그것을 가능하게 할 트리거를 어떻게 설정해야하는가?
2. 가장 확실하게 지금 당장 올린 csv파일을 불러올 수 있도록 하는 조건이 무엇인가? 
(생각한 방법은 현재 존재하는 csv model의 인스턴트가 가지는 id중 가장 큰 id를 가져오는 건데.. 이 방법이 정확하게 불러올 수 있는 조건이 아닌 것 같아서 의논 필요)

**Comment by kmju1997** [comment]
char field를 primary key화 하는 법
![image](https://user-images.githubusercontent.com/19407354/28367585-7082f39c-6ccc-11e7-9756-3eebea8f0d43.png)

**Comment by rlrlaa123** [comment]
1. 이건 나중에 api 데이터 앱에 뿌리는거 성공시키고 고민해야 할듯 현재로선 방안을 모르겠음
2. admin페이지에서 csv파일을 업데이트만 시키면 2번 의문점에 대한 해결책이 될듯

수정해야할 부분 1번은 다른 issue로 올리겠음 @kmju1997 가 해결바람 :') model에 file 타입 필드로 만들면 될듯

**Comment by rlrlaa123** [comment]
아 그리고 csv 파일 데이터 파싱은 python 기본 라이브러리중 csv 라이브러리를 사용하면 됨.

**Comment by kmju1997** [comment]
파싱하는 거 pandas로는 일단 시도해봤는데 성공... csv 라이브러리로 불러오려니까 utf 에러가 계속 납니당

**Comment by rlrlaa123** [comment]
MySQL로 csv파일 올림.
